---
title: "team_analysis"
author: "Andrew Pike"
date: "25/09/2022"
output: html_document
---
```{r load_package, echo = FALSE, warning = FALSE, message = FALSE}
pkgload::load_all()
library(caret)
```


## Load Data 

```{r read_tables, include=FALSE}
team_logs <- read_team_logs()

manager_table <- read_manager_table()

standings_table <- read_standings_table()
```

## Table Joins
```{r join_tables}
team_log_w_manager <- join_manager_table(team_logs, manager_table)
# need to normalize moves
full_table <- join_standings_table(team_log_w_manager, standings_table) %>%
    normalize_gp()

totals_table <- full_table %>%
    dplyr::filter(
        Name == "Total",
        Manager != "Collin",
        Manager != "Noel"
    ) %>%
    dplyr::mutate(
        Manager = as.factor(Manager),
        division = as.factor(division)
    ) %>%
    dplyr::select(
        -c(
            "W-L-T",
            "Div",
            "team_name",
            "GWG",
            "SOG",
            "Name",
            "division",
            "Pct",
            "Pts",
            "Waiver",
            "pre_playoff_rank"
        )
    )
```

## Games Played

```{r games played plot, echo=FALSE}
totals_table %>%
    dplyr::group_by(
        year
    ) %>%
    plotly::plot_ly(
        x = ~year,
        y = ~GP_norm,
        type = "bar",
        color = ~Manager,
        text = ~ paste0(
            Manager,
            " : ",
            final_rank
        )
    )
```


```{r, echo = FALSE, warning = FALSE, message = FALSE}
totals_table %>%
    plotly::plot_ly(
        x = ~final_rank,
        y = ~GP_norm,
        type = "scatter",
        color = ~Manager,
        text = ~Manager
    )
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}
numeric_table <- totals_table %>%
    dplyr::ungroup() %>%
    dplyr::select_if(is.numeric) %>%
    dplyr::select(
        !year
    )

cor_numeric <- cor(numeric_table)
```


## Build corrplot

```{r, echo = FALSE, warning = FALSE, message = FALSE}
corrplot::corrplot.mixed(cor_numeric, upper = "ellipse", lower = "number", tl.pos = "lt")
```

## Drop high correlation features

```{r, echo = FALSE, warning = FALSE, message = FALSE}

```

## Numeric Skim Table
```{r build_regression, echo = FALSE, warning = FALSE, message = FALSE}
skim_table_numeric <- skimr::skim(numeric_table)

reactable::reactable(skim_table_numeric, pagination = F)
```

```{r dummy_col_creation, echo = FALSE, warning = FALSE, message = FALSE}
dummy_totals <- caret::dummyVars(final_rank ~ ., data = totals_table)

totals_table_w_dummies <- tibble::as_tibble(
    stats::predict(
        dummy_totals,
        newdata = totals_table
    )
)

totals_table_w_dummies <- dplyr::bind_cols(
    final_rank = totals_table$final_rank,
    totals_table_w_dummies
)

cor_totals <- cor(totals_table_w_dummies)

corrplot::corrplot.mixed(cor_totals, upper = "ellipse", lower = "number", tl.pos = "lt")
```


## Test for Near Zero Variance

```{r build_model, echo = FALSE, warning = FALSE, message = FALSE}
caret::nearZeroVar(totals_table_w_dummies, saveMetrics = T)
```

## Split into test/train split

```{r build_test_train, echo = FALSE, warning = FALSE, message = FALSE}
set.seed(2)

train_row_numbers <- caret::createDataPartition(
    totals_table_w_dummies$final_rank,
    p = 0.75,
    list = FALSE
)

training_set <- totals_table_w_dummies[train_row_numbers, ]

test_set <- totals_table_w_dummies[-train_row_numbers, ]

skim_table_training <- skimr::skim(training_set)

reactable::reactable(skim_table_training, pagination = F)

skim_table_test <- skimr::skim(test_set)

reactable::reactable(skim_table_test, pagination = F)
```

## Train Model

```{r, echo = FALSE, warning = FALSE, message = FALSE}
set.seed(2)

gbm_fit <- caret::train(
    final_rank ~ .,
    data = training_set,
    method = "gbm"
)
```